/**
 * A/B Test Integration Types
 *
 * Type definitions for A/B test experiment tracking, including:
 * 1. Experiment status and configuration
 * 2. Variant definitions with metrics
 * 3. Statistical significance calculations
 * 4. Conversion and revenue impact analysis
 */

import type { Channel } from "./attribution";

// =============================================================================
// 1. CORE EXPERIMENT TYPES
// =============================================================================

/**
 * Status of an A/B test experiment.
 * - running: Actively collecting data
 * - paused: Temporarily stopped
 * - completed: Reached statistical significance or ended
 * - draft: Not yet started
 */
export type ExperimentStatus = "running" | "paused" | "completed" | "draft";

/**
 * Type of metric being tested in an A/B experiment.
 * - conversion: Binary success/failure outcome
 * - revenue: Monetary value per visitor
 * - engagement: Time, clicks, or interaction metrics
 */
export type ABTestMetricType = "conversion" | "revenue" | "engagement";

/**
 * Confidence level for statistical significance.
 */
export type ConfidenceLevel = 90 | 95 | 99;

// =============================================================================
// 2. VARIANT TYPES
// =============================================================================

/**
 * A single variant in an A/B test.
 * Typically "A" is control and "B" is treatment.
 */
export interface Variant {
  /** Unique identifier for this variant */
  id: string;
  /** Display name (e.g., "Control", "Treatment", "Variant A") */
  name: string;
  /** Brief description of what this variant tests */
  description?: string;
  /** Whether this is the control variant */
  isControl: boolean;
  /** Traffic allocation percentage (0-100) */
  trafficAllocation: number;
}

/**
 * Metrics for a single variant.
 */
export interface VariantMetrics {
  /** The variant these metrics belong to */
  variantId: string;
  /** Number of unique visitors assigned to this variant */
  visitors: number;
  /** Number of conversions (goals completed) */
  conversions: number;
  /** Conversion rate = conversions / visitors */
  conversionRate: number;
  /** Total revenue generated by this variant (in dollars) */
  revenue: number;
  /** Revenue per visitor = revenue / visitors */
  revenuePerVisitor: number;
  /** Average order value for converters (in dollars) */
  averageOrderValue: number;
  /** Bounce rate percentage */
  bounceRate: number;
  /** Average session duration in seconds */
  avgSessionDuration: number;
}

// =============================================================================
// 3. STATISTICAL ANALYSIS TYPES
// =============================================================================

/**
 * Statistical significance result for a variant comparison.
 */
export interface StatisticalSignificance {
  /** Whether the result is statistically significant */
  isSignificant: boolean;
  /** P-value from the statistical test (lower = more significant) */
  pValue: number;
  /** Confidence level percentage (90, 95, or 99) */
  confidenceLevel: ConfidenceLevel;
  /** Standard error of the difference */
  standardError: number;
  /** Lower bound of the confidence interval */
  confidenceIntervalLow: number;
  /** Upper bound of the confidence interval */
  confidenceIntervalHigh: number;
  /** Minimum detectable effect size */
  minimumDetectableEffect: number;
  /** Required sample size to reach significance */
  requiredSampleSize: number;
  /** Current sample size */
  currentSampleSize: number;
  /** Estimated days to reach significance at current rate */
  estimatedDaysToSignificance: number | null;
}

/**
 * Comparison between control and treatment variants.
 */
export interface VariantComparison {
  /** Control variant ID */
  controlId: string;
  /** Treatment variant ID */
  treatmentId: string;
  /** Absolute lift in conversion rate (treatment - control) */
  absoluteLift: number;
  /** Relative lift percentage = (treatment - control) / control * 100 */
  relativeLift: number;
  /** Revenue lift in dollars */
  revenueLift: number;
  /** Revenue lift percentage */
  revenueLiftPercent: number;
  /** Statistical significance of the conversion rate difference */
  conversionSignificance: StatisticalSignificance;
  /** Statistical significance of the revenue difference */
  revenueSignificance: StatisticalSignificance;
  /** Probability that treatment is better than control (Bayesian) */
  probabilityToBeBest: number;
  /** Expected loss if wrong variant is chosen (in dollars) */
  expectedLoss: number;
}

// =============================================================================
// 4. EXPERIMENT TYPES
// =============================================================================

/**
 * Trend data point for experiment metrics over time.
 */
export interface ExperimentTrendPoint {
  /** ISO 8601 date string */
  date: string;
  /** Variant ID this data point belongs to */
  variantId: string;
  /** Cumulative conversion rate at this point */
  conversionRate: number;
  /** Cumulative visitors at this point */
  visitors: number;
  /** Cumulative conversions at this point */
  conversions: number;
}

/**
 * Complete A/B test experiment definition.
 */
export interface Experiment {
  /** Unique identifier for this experiment */
  id: string;
  /** Human-readable experiment name */
  name: string;
  /** Detailed description of the hypothesis being tested */
  description: string;
  /** Current status of the experiment */
  status: ExperimentStatus;
  /** Type of primary metric being tested */
  metricType: ABTestMetricType;
  /** Page or feature being tested */
  targetPage: string;
  /** Marketing channel(s) this experiment applies to */
  channels: Channel[];
  /** ISO 8601 timestamp when the experiment started */
  startedAt: string;
  /** ISO 8601 timestamp when the experiment ended (if completed) */
  endedAt?: string;
  /** Variants being tested (typically 2, A and B) */
  variants: Variant[];
  /** Metrics for each variant */
  variantMetrics: VariantMetrics[];
  /** Comparison results between variants */
  comparison: VariantComparison;
  /** Trend data for visualization */
  trend: ExperimentTrendPoint[];
  /** User who created the experiment */
  createdBy: string;
  /** Tags for filtering/grouping experiments */
  tags: string[];
}

// =============================================================================
// 5. SUMMARY TYPES
// =============================================================================

/**
 * Summary statistics for all A/B tests.
 */
export interface ABTestSummary {
  /** Total number of experiments */
  totalExperiments: number;
  /** Number of currently running experiments */
  runningExperiments: number;
  /** Number of completed experiments */
  completedExperiments: number;
  /** Number of experiments that found a winner */
  successfulExperiments: number;
  /** Average lift across winning experiments */
  averageWinningLift: number;
  /** Total revenue impact from all experiments (in dollars) */
  totalRevenueImpact: number;
  /** Total additional conversions from winning variants */
  totalAdditionalConversions: number;
  /** Average time to reach significance (in days) */
  avgTimeToSignificance: number;
  /** Experiment with the highest lift */
  topPerformingExperiment: string;
}

// =============================================================================
// 6. COMBINED A/B TEST DATA
// =============================================================================

/**
 * Complete A/B test data response.
 * Contains all experiments, summary, and metadata.
 */
export interface ABTestData {
  /** List of all experiments */
  experiments: Experiment[];
  /** Summary statistics */
  summary: ABTestSummary;
  /** Time range for this analysis */
  timeRange: {
    /** ISO 8601 date for the start of the analysis period */
    start: string;
    /** ISO 8601 date for the end of the analysis period */
    end: string;
  };
  /** ISO 8601 timestamp when this data was generated */
  generatedAt: string;
}

// =============================================================================
// 7. API RESPONSE TYPE
// =============================================================================

/**
 * API response wrapper for A/B test data.
 */
export interface ABTestResponse {
  /** Whether the request was successful */
  success: boolean;
  /** The A/B test data payload */
  data: ABTestData;
  /** ISO 8601 timestamp of the response */
  timestamp: string;
  /** Error message (present on failure) */
  error?: string;
}
